# Generated by Django 4.2.7 on 2023-11-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_personal_data',
            name='sex',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
    ]
