# Generated by Django 4.2.7 on 2023-11-24 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_alter_student_personal_data_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_personal_data',
            name='curp',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[a-zA-z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='student_personal_data',
            name='father_lastname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Just letters allowed')]),
        ),
        migrations.AlterField(
            model_name='student_personal_data',
            name='mother_lastname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Just letters allowed')]),
        ),
        migrations.AlterField(
            model_name='student_personal_data',
            name='names',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Just letters allowed')]),
        ),
    ]
